#!/usr/bin/env bash


# Herbstluftwm start
hc() {
    herbstclient "$@"
}

hc set_layout horizontal


hc emit_hook reload

# KEYBINDINGS

# remove all existing keybindings
hc keyunbind --all

# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1  # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

# hc keybind $Mod-Shift-x quit
# hc keybind $Mod-F2 reload
# hc keybind $Mod-Shift-q close
# hc keybind $Mod-q close

#Most of the keybindings have been set in sxhkd config file
#you can set them also here

#reload sxhkd - see keybind in sxhkd
#hc keybind $Mod-Shift-s  pkill -USR1 -x sxhkd

# MOVEMENTS

# focusing clients
#hc keybind $Mod-Left  focus left
#hc keybind $Mod-Down  focus down
#hc keybind $Mod-Up    focus up
#hc keybind $Mod-Right focus right
#hc keybind $Mod-h     focus left
#hc keybind $Mod-j     focus down
#hc keybind $Mod-k     focus up
#hc keybind $Mod-l     focus right

# moving clients to ... on single Monitor
#hc keybind $Mod-Shift-Left  shift left
#hc keybind $Mod-Shift-Down  shift down
#hc keybind $Mod-Shift-Up    shift up
#hc keybind $Mod-Shift-Right shift right
#hc keybind $Mod-Shift-h     shift left
#hc keybind $Mod-Shift-j     shift down
#hc keybind $Mod-Shift-k     shift up
#L hc keybind $Mod-Shift-l     shift right

# moving clients to ... on dual monitor
hc keybind $Mod-Shift-h chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
hc keybind $Mod-Shift-Left chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
hc ke#ybind $Mod-Shift-j chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
hc keybind $Mod-Shift-Down chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
hc keybind $Mod-Shift-k chain , lock , shift_to_monitor -r , focus_monitor -r , unlock
hc keybind $Mod-Shift-Up chain , lock , shift_to_monitor -r , focus_monitor -r , unlock
hc keybind $Mod-Shift-l chain , lock , shift_to_monitor -r , focus_monitor -r , unlock
hc keybind $Mod-Shift-Right chain , lock , shift_to_monitor -r , focus_monitor -r , unlock

# FRAMES

# create an empty frame at the specified direction
#hc keybind $Mod-u       split   bottom  0.5
#hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
#hc keybind $Mod-Control-space split explode
# remove frame
#hc keybind $Mod-Control-m remove
#hc keybind $Mod-o split explode

# resizing frames
resize=0.05
hc keybind $Mod-Control-h       resize left +$resize
hc keybind $Mod-Control-j       resize down +$resize
hc keybind $Mod-Control-k       resize up +$resize
hc keybind $Mod-Control-l       resize right +$resize
hc keybind $Mod-Control-Left    resize left +$resize
hc keybind $Mod-Control-Down    resize down +$resize
hc keybind $Mod-Control-Up      resize up +$resize
hc keybind $Mod-Control-Right   resize right +$resize

# TAGS or WORKSPACES

#names to display in menu
#tag_names=( {1..10} )
#tag_names=("Web" "Chat" "Edit" "Misc" "Virtual" "Media" "Steam" "Work" "Music")
tag_names=( "" "" "" "" "" "" "" "" "" )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# layouting
#hc keybind $Mod-s floating toggle
#hc keybind $Mod-f fullscreen toggle
#hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max  \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus on ...
#hc keybind $Mod-BackSpace   cycle_monitor
#hc keybind $Mod-Tab         use_index +1 --skip-visible
#hc keybind $Mod-Shift-Tab   use_index -1 --skip-visible
#hc keybind Control-Mod1-Left    focus left
#hc keybind Control-Mod1-Up      focus up
#hc keybind Control-Mod1-Right   focus right
#hc keybind Control-Mod1-Down    focus down
#hc keybind Mod1-Tab         use_index +1 --skip-visible
#hc keybind Mod1-Shift-Tab   use_index -1 --skip-visible
#hc keybind $Mod-c cycle
# hc keybind $Mod1-i jumpto urigent


###########
#  THEME  #
###########

###########
#  THEME  #
###########
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_normal_color '#000000'
hc set frame_border_active_color '#242424'
hc set frame_bg_normal_color '#000000'
hc set frame_bg_active_color '#2e8b57'
hc set frame_border_width 1
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0
hc set frame_padding 0
hc set smart_frame_surroundings 0
hc set smart_window_surroundings 0


hc attr theme.active.color '#2e8b57'
hc attr theme.normal.color '#000000'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 1
hc attr theme.active.border_width 8
hc attr theme.normal.border_width 8
hc attr theme.floating.border_width 8
hc attr theme.floating.color orange
#hc attr theme.floating.outer_color black
hc attr theme.floating.outer_width 1
hc attr theme.floating.inner_width 1
hc attr theme.active.tab_color '#27450B'
hc attr theme.active.tab_outer_color '#61875F'
hc attr theme.active.tab_title_color '#cecece'
#hc attr theme.active.inner_color '#3E4A00'
#hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

# hc and , attr theme.title_height 15 \
#        , attr theme.title_depth 3 \
#        , attr theme.title_color white \
#        , attr theme.normal.title_color '#dedede'

hc set window_gap 10
hc set focus_follows_mouse 1
hc set mouse_recenter_gap 20


# RULES
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule floatplacement=center
hc rule instance="Floating" manage=on floating=on floatplacement=center floating_geometry=800x800
hc rule instance="Float" manage=on floating=on floatplacement=center 
#hc rule focus=off # normally do not focus new clients

#assign applications to workspaces or tags
hc rule class~'(brave|Brave-browser|Chromium|Google-chrome)' tag='' switchtag=on focus=on
hc rule class='Spotify' tag='' switchtag=on focus=on
hc rule class='subl' tag=''  switchtag=on focus=on
hc rule class~'(discord|Discord)' tag='' switchtag=on focus=on
hc rule class~'(vlc|mpv|Mpv)' tag='' focus=on switchtag=on fullscreen=on hook=fullscreen
hc rule class~'(VirtualBox Manager|Vmplayer)' tag='' switchtag=on focus=on
hc rule class~'(Thunar|Pcmanfm|Nemo)' tag='' switchtag=on focus=on
hc rule class~'(Shotcut|Gpick|gpick)' tag='' floating=on
hc rule class~'(gimp|Gimp)' tag='' switchtag=on focus=on
hc rule class~'(Zathura|zathura|Lxappearance|Pavucontrol|)' floating=on floatplacement=smart
hc rule class='Steam' tag='' focus=off fullscreen=on
hc rule title~'.*Steam.*' tag='' focus=off fullscreen=on
hc rule class='Steam' tag='' title~'.*Barátlista.*' floating=off focus=on
hc rule class='zoom' not title~'.*Meeting.*' floating=on focus=off

# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' floating=on focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on 
#hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock


#Dualmonitor setup
hc detect_monitors
#hc set_monitors 3440x2160+0+0 400x2160+3440+0 
#hc set_monitors 3840x2160+0+0 1080x1920+4920+0

#hc remove_monitor 1


#room for polybar on both monitors
# find the panel
[ -x "$panel" ] || panel=$HOME/.config/polybar/launch.sh
#panel=$HOME/.local/bin/herbstbar
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
start it on each monitor
"$panel" $monitor &
#hc pad 0 "" "" 25
hc pad 0 30 0 0  
#hc pad 0 "" 5
#hc pad 0 "" "" "" 5
done
sxhkd &
$TERMINAL --class Float &
hc split vertical 0.6; hc remove